dependencies:
- name: template-node-react-rameshkr
  version: 1.0.0-4
  repository: http://artifactory.garage-devtools-sfo-rhos.us-east.containers.appdomain.cloud/artifactory/generic-local/garage-devtools-sfo/
