dependencies:
- name: template-node-react-rameshkr
  version: 1.0.0-<build tag version>
  repository: https://artifactory.garage-devtools-sfo-rhos.us-east.containers.appdomain.cloud/generic-local/garage-devtools-sfo/
